spring.application.name=ecommerce

# Configuración de la conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/smartcart
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
# 'update' mantiene los datos y solo aplica cambios en la estructura
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Formatear el SQL en consola para lectura fácil
spring.jpa.properties.hibernate.format_sql=true